# Re-apply a clone's branding on top of Fermosa source. Idempotent — safe to
# re-run after pulling upstream fixes. Reads scripts/brand.tokens.psd1, which
# only exists inside a clone (copy brand.tokens.example.psd1 and fill it in) —
# so running this in the Fermosa source repo fails safe.
# This is the MASTER copy: sync-from-fermosa.ps1 copies it into each clone.
# Any new file that hard-codes a brand string (display name, fermosa.local, …)
# MUST be added to $files below, or every clone ships Fermosa branding there.
# Uses literal, case-sensitive String.Replace so localStorage keys (fermosa.*),
# dev seed emails (@fermosa.test), and the internal @fermosa/shared package name
# are deliberately left alone.
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$tokens = Join-Path $PSScriptRoot 'brand.tokens.psd1'
if (-not (Test-Path -LiteralPath $tokens)) {
  throw "scripts/brand.tokens.psd1 not found. In a clone, copy brand.tokens.example.psd1 to brand.tokens.psd1 and fill it in. Never run this in the Fermosa source repo."
}
$t = Import-PowerShellDataFile $tokens

# Ordered, most-specific first. Each is a literal find -> replace.
$pairs = @()
$pairs += ,@('Fermosa Skin Care Clinic', $t.Display)
$pairs += ,@('Fermosa Attendance',       $t.Title)
$pairs += ,@('"scheme": "fermosa"',       ('"scheme": "' + $t.Scheme + '"'))
$pairs += ,@('ph.fermosa.attendance',     $t.Bundle)
$pairs += ,@('fermosa-attendance',        $t.Slug)
$pairs += ,@('fermosa-mark.jpg',          'logo-mark.jpg')
$pairs += ,@('fermosa-wordmark.jpg',      'logo-wordmark.jpg')
$pairs += ,@('fermosa.local',             $t.Domain)
$pairs += ,@('across all 22 branches',    'across your branches')
$pairs += ,@('SKIN CARE CLINIC',          'ATTENDANCE')
$pairs += ,@('Skin Care Clinic',          $t.Subtitle)
$pairs += ,@('Fermosa',                   $t.Display)

$files = @(
  'apps\dashboard\index.html',
  'apps\dashboard\vite.config.ts',
  'apps\dashboard\src\components\Layout.tsx',
  'apps\dashboard\src\components\PayslipView.tsx',
  'apps\dashboard\src\pages\Login.tsx',
  'apps\dashboard\src\pages\Overview.tsx',
  'apps\dashboard\src\pages\TimeClock.tsx',
  'apps\dashboard\src\pages\KioskMode.tsx',
  'apps\dashboard\src\pages\KioskSetup.tsx',
  'apps\dashboard\src\pages\EmployeeForm.tsx',
  'packages\shared\src\constants.ts',
  'scripts\bulk-import\import.mjs',
  'scripts\bulk-import\README.md',
  'supabase\functions\admin-users\index.ts',
  # company seed row — name must stay in step with import.mjs COMPANY_NAME
  'supabase\migrations\20260714000003_company_seed.sql',
  'apps\mobile\app.json',
  'apps\mobile\src\app\login.tsx',
  'README.md'
)
$enc = New-Object System.Text.UTF8Encoding($false)
foreach ($rel in $files) {
  $p = Join-Path $Root $rel
  if (-not (Test-Path -LiteralPath $p)) { Write-Warning "skip missing $rel"; continue }
  $c = [IO.File]::ReadAllText($p)
  foreach ($pr in $pairs) { $c = $c.Replace($pr[0], $pr[1]) }
  [IO.File]::WriteAllText($p, $c, $enc)
}

# username.test.ts: only the default login domain changes. Its @fermosa.test /
# mixed-case fixtures are deliberate test inputs and must NOT be rebranded.
$ut = Join-Path $Root 'packages\shared\src\username.test.ts'
if (Test-Path -LiteralPath $ut) {
  $c = [IO.File]::ReadAllText($ut); $c = $c.Replace('fermosa.local', $t.Domain)
  [IO.File]::WriteAllText($ut, $c, $enc)
}

# backup workflow label — lowercase 'fermosa' only (no capital in this file)
$bk = Join-Path $Root '.github\workflows\backup.yml'
if (Test-Path -LiteralPath $bk) {
  $c = [IO.File]::ReadAllText($bk); $c = $c.Replace('fermosa', $t.Label)
  [IO.File]::WriteAllText($bk, $c, $enc)
}

# Regenerate the one-paste migration bundle (files applied in filename order).
$migDir = Join-Path $Root 'supabase\migrations'
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('-- ' + $t.Display + ' — full schema. Paste into the Supabase SQL Editor and Run,')
[void]$out.AppendLine('-- OR apply with: npx supabase@latest db push (see docs/SETUP-' + $t.Display.Replace(' ','') + '.md).')
[void]$out.AppendLine('-- Generated by scripts/rebrand.ps1 — do not hand-edit; edit supabase/migrations/*.sql.')
[void]$out.AppendLine('')
foreach ($f in (Get-ChildItem $migDir -Filter *.sql | Sort-Object Name)) {
  [void]$out.AppendLine('-- ============================================================')
  [void]$out.AppendLine('-- ' + $f.Name)
  [void]$out.AppendLine('-- ============================================================')
  [void]$out.AppendLine([IO.File]::ReadAllText($f.FullName))
  [void]$out.AppendLine('')
}
[IO.File]::WriteAllText((Join-Path $Root 'supabase\all-migrations.sql'), $out.ToString(), $enc)
Write-Host ('Rebranded to "' + $t.Display + '". Review with: git diff')
